name: Action worrkflow which trigger with other events like pull_request...etc

# on: [push, pull_request]

on:
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello Im triggerred with pull_request activities"
